version: "3.9"

volumes:
  db-store:
  pma-session-store:

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /data

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /data

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  pma:
    image: phpmyadmin/phpmyadmin:5.2.0
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME:-phper}
      - PMA_PASSWORD=${DB_PASSWORD:-secret}
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - pma-session-store:/sessions
